apiVersion: apps/v1
kind: Deployment
metadata:
  name: boldbi-proxy-deployment
  namespace: bi-bv
  labels:
    app: boldbi-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boldbi-proxy
  template:
    metadata:
      labels:
        app: boldbi-proxy
    spec:
      containers:
        - name: boldbi-proxy
          image: mallucharan/boldbi-proxy:latest
          ports:
            - containerPort: 8080
          env:
            - name: BOLDBI_API_HOST
              value: "http://bi-api-service:6005/boldbi"
            - name: BOLDBI_API_USERNAME
              value: "sa@sa.com" # Replace with your username
            - name: BOLDBI_API_EMBEDSECRET
              value: "uY2IcsuFpvtnyeZ2" # Replace with your embed secret
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: boldbi-proxy-service
  namespace: bi-bv
spec:
  selector:
    app: boldbi-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

--------------------------

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boldbi-proxy-ingress
  namespace: bi-bv
  labels:
    app.kubernetes.io/name: boldbi-proxy
    app.kubernetes.io/managed-by: custom
  annotations:
    konghq.com/https-redirect-status-code: '308'
    konghq.com/protocols: https
    konghq.com/strip-path: 'true'
    kubernetes.io/ingress.class: kong
    kubernetes.io/tls-acme: 'true'
spec:
  tls:
    - hosts:
        - k-multi.bolbi-poc.cherryy.ca
      secretName: k-multi-bolbi-poc-cherryy-ca-ingress-secret
  rules:
    - host: k-multi.bolbi-poc.cherryy.ca
      http:
        paths:
          - path: /boldbiinternal/
            pathType: ImplementationSpecific
            backend:
              service:
                name: bi-api-service
                port:
                  number: 80
